Program 0x00
Bgm 94 94


Program 0x01
Bgm 94 94
AreaSettings 0 -1
	SetProgressFlag 0x4807
	SetEvent "103a" Type 3
	SetJump Type 2 World TT Area 0 Entrance 0 LocalSet 214 FadeType 16386
	SetPartyMenu 0


Program 0x63
Bgm 61 61
AreaSettings 16 -1
	SetProgressFlag 0x484E
	SetJump Type 2 World EH Area 0 Entrance 0 LocalSet 114 FadeType 16386
	SetPartyMenu 0


Program 0x41
Bgm 61 61
AreaSettings 16 -1
	SetJump Type 1 World EH Area 21 Entrance 0 LocalSet 0 FadeType 16386
	SetPartyMenu 0
